### ISSUE TITLE
Maven Multi Threaded

### ISSUE THREAD

**Issue by zekronium** [vsilaev/tascalate-async-await#15]
We are using multiple threads to build our maven projects

Tascalate is not marked as thread safe and maven is giving us warnings

Is it actually not threadsafe or just not marked as such

**Comment by vsilaev** [comment]
> Is it actually not threadsafe or just not marked as such

Never tried it in multi-threaded builds. Though, there is nothing mutable in the plugin itself, the only question is how Maven orchestrate phases in muti-threaded runs

**Comment by zekronium** [comment]
Afaik, it executes the phases themselves with higher concurrency
