### ISSUE TITLE
Passing CompletionStage between methods bug

### ISSUE THREAD

**Issue by brr53** [vsilaev/tascalate-async-await#19]
Dear @vsilaev , thank you again for the great work on Tascalate!

I've noticed a small bug which I have not been able to locate the error in the source for. Here is the code to reproduce the result:

Java version: 11

      public class UnwrappedCompletionStageTest {
        public static void main(String[] args) {
          test3();
        }
      
        @async
        static CompletionStage<String> test1() {
          return CallContext.async("hello");
        }
      
        // in non test code we would have awaited other methods inside test2() - so we need the @async tag
        @async
        static CompletionStage<String> test2() {
          //await some things (hence the @async tag)
          return test1();
        }
      
        @async
        static void test3() {
          var s = await(test2());
          System.out.println(s);
        }
      }

I get null with the above code when we should have "hello". It works without using @async for test2(). However in non test code I have things I want to await in that method so we need @async

**Comment by vsilaev** [comment]
Closing as not an issue -- user code violates basic documented usage guidelines. There is no `return VALUE` possible in `@async` methods, instead `return async(VALUE)` should be used.
