### ISSUE TITLE
Tascalate vs Virtual Threads

### ISSUE THREAD

**Issue by zekronium** [vsilaev/tascalate-async-await#22]
Hi,

From my understanding of the code, tascalate to a degree performs similar operations to virtual threads (as in moves stack to heap and so on). 

Have you with your more in depth understanding of tascate compared performance of tascalte vs virtual threads and how each one scales?

If so, are there potential benefits/caveats to tascalate versus virtual threads? The main caveat I see is the ability to use threadlocals since the “carrier” thread is guaranteed to be the same with tascalate, which is not the case with virtual threads.

Maybe we can benchmark it further?
What are your opinions comparing tascalate vs virtual threads

**Comment by vsilaev** [comment]
Sorry for delay with answer, but anyway...
It looks that there is already an implementation of async/await based on `VirtualThread`-s: https://github.com/AugustNagro/java-async-await

You can create your own benchmark and do a comparison.  

Actually, it's not a question of  replacing continuations-based implementation (Tascalate JavaFlow)  with VirtualThreads, it's far more complex. It's necessary to rewrite `@async` methods to handle chunks of the code between `await`. For example, EA Async rewrites code to the chained `CompletionStage` execution directly...  I have no plans to rewrite this engine (continuations-based) to the VirtualThread (where individual code chunks are sent to the VirtualThread when necessary) - it means writing brand new project.

> If so, are there potential benefits/caveats to tascalate versus virtual threads? The main caveat I see is the ability to use threadlocals since the “carrier” thread is guaranteed to be the same with tascalate, which is not the case with virtual threads.

Tascalate Async/Await does not guarantee that code will be resumed on the same thread, it's `Scheduler`-dependent. Also, it requires specific contextualizer for `Scheduler` (typically, using `ContextVar.relay(...)`). Java has own JEP-s to assist with context sharing:
https://openjdk.org/jeps/429
https://openjdk.org/jeps/446
